CREATE TABLE "world" (id INTEGER PRIMARY KEY CHECK(id=1), "name" TEXT, "seed_name" TEXT, "seed" INTEGER, "uid" INTEGER, "generation_version" INTEGER, "needs_data" INTEGER, "time" REAL, "location_version" INTEGER, "locations_generated" INTEGER);
CREATE TABLE chunks (id INTEGER PRIMARY KEY, "native_index" INTEGER, "size_level" INTEGER, "native_version" INTEGER, "source_file" TEXT UNIQUE, "object_count" INTEGER);
CREATE TABLE "objects" (id INTEGER PRIMARY KEY, chunk INTEGER NOT NULL REFERENCES chunks(id) ON DELETE CASCADE, "chunk_order" INTEGER NOT NULL, prefab_hash INTEGER NOT NULL, prefab TEXT, "x" REAL, "y" REAL, "z" REAL, rotation_x REAL, rotation_y REAL, rotation_z REAL, "persistent" INTEGER, distant INTEGER, "network_type" INTEGER, "flags" INTEGER, "raw_data" BLOB);
CREATE TABLE "properties" ("object_id" INTEGER NOT NULL REFERENCES "objects"(id) ON DELETE CASCADE, "key_hash" INTEGER NOT NULL, "key" TEXT, type TEXT NOT NULL, "integer" INTEGER, "real" REAL, "text" TEXT, x REAL,y REAL,z REAL,w REAL,"blob" BLOB, "raw_value" BLOB, PRIMARY KEY("object_id",type,"key_hash")) WITHOUT ROWID;
CREATE TABLE "connections" ("object_id" INTEGER PRIMARY KEY REFERENCES "objects"(id) ON DELETE CASCADE, type INTEGER, "type_name" TEXT, "connection_hash" INTEGER);
CREATE TABLE "zones" (x INTEGER,z INTEGER,PRIMARY KEY(x,z)) WITHOUT ROWID;
CREATE TABLE "locations" (id INTEGER PRIMARY KEY, prefab_hash INTEGER,prefab TEXT,"x" REAL,"y" REAL,"z" REAL,"placed" INTEGER);
CREATE TABLE "world_keys" ("source" TEXT,"key" TEXT,PRIMARY KEY("source","key")) WITHOUT ROWID;
CREATE TABLE "player_history" (id INTEGER PRIMARY KEY,"platform_id" TEXT,"name" TEXT,"server_name" TEXT,"playfab_id" TEXT);
CREATE TABLE "events" (id INTEGER PRIMARY KEY,type TEXT,"name" TEXT,"time" REAL,"x" REAL,"y" REAL,"z" REAL,"json" TEXT);
CREATE TABLE "containers" ("object_id" INTEGER PRIMARY KEY REFERENCES "objects"(id) ON DELETE CASCADE,version INTEGER,"item_count" INTEGER,"decode_status" TEXT);
CREATE TABLE "inventory" (id INTEGER PRIMARY KEY,"object_id" INTEGER REFERENCES "containers"("object_id") ON DELETE CASCADE,"item_order" INTEGER,prefab_hash INTEGER,prefab TEXT,"stack" INTEGER,"quality" INTEGER,"durability" REAL,"x" INTEGER,"y" INTEGER,"equipped" INTEGER,"picked_up" INTEGER,"variant" INTEGER,"crafter_id" INTEGER,"crafter_name" TEXT,"world_level" INTEGER,"cheated" INTEGER,"flags" INTEGER,"extra_flags" INTEGER);
CREATE TABLE "item_data" ("item_id" INTEGER REFERENCES "inventory"(id) ON DELETE CASCADE,"key" TEXT,"value" TEXT,PRIMARY KEY("item_id","key")) WITHOUT ROWID;
CREATE TABLE "dungeons" ("object_id" INTEGER PRIMARY KEY REFERENCES "objects"(id) ON DELETE CASCADE,"room_count" INTEGER NOT NULL);
CREATE TABLE "rooms" ("object_id" INTEGER REFERENCES "dungeons"("object_id") ON DELETE CASCADE,"room_order" INTEGER,prefab_hash INTEGER,prefab TEXT,"x" REAL,"y" REAL,"z" REAL,rotation_x REAL,rotation_y REAL,rotation_z REAL,PRIMARY KEY("object_id","room_order")) WITHOUT ROWID;
CREATE TABLE "terrain" ("object_id" INTEGER PRIMARY KEY REFERENCES "objects"(id) ON DELETE CASCADE,version INTEGER,"operations" INTEGER,"last_x" REAL,"last_y" REAL,"last_z" REAL,"last_radius" REAL,"vertex_count" INTEGER,"pixel_count" INTEGER);
CREATE TABLE "terrain_heights" ("object_id" INTEGER REFERENCES "terrain"("object_id") ON DELETE CASCADE,"index" INTEGER,"level" REAL,"smooth" REAL,PRIMARY KEY("object_id","index")) WITHOUT ROWID;
CREATE TABLE "terrain_paint" ("object_id" INTEGER REFERENCES "terrain"("object_id") ON DELETE CASCADE,"index" INTEGER,"r" REAL,"g" REAL,"b" REAL,"a" REAL,PRIMARY KEY("object_id","index")) WITHOUT ROWID;
CREATE TABLE "schema_guide" ("name" TEXT PRIMARY KEY, description TEXT NOT NULL);
ALTER TABLE objects ADD COLUMN zdo_user INTEGER NOT NULL DEFAULT -1;
ALTER TABLE objects ADD COLUMN zdo_id INTEGER NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX objects_zdo ON objects(zdo_user,zdo_id);
ALTER TABLE connections ADD COLUMN target_user INTEGER;
ALTER TABLE connections ADD COLUMN target_id INTEGER;
CREATE INDEX objects_chunk ON objects(chunk);
CREATE INDEX properties_key ON properties(key_hash,type);
CREATE UNIQUE INDEX inventory_position ON inventory(object_id,x,y);

CREATE TABLE migration (id INTEGER PRIMARY KEY CHECK(id=1),native_save INTEGER,format_version INTEGER,source TEXT,started_at TEXT,object_count INTEGER);
CREATE TABLE world_data (key TEXT PRIMARY KEY, data BLOB NOT NULL) WITHOUT ROWID;
