using System;using System.IO;using System.Reflection;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using UnityEditor;
public static class ConstructionScrollChecks {
public static void Run(){
AppDomain.CurrentDomain.AssemblyResolve+=(s,a)=>{var p=Path.GetFullPath("../../../Libs/"+new AssemblyName(a.Name).Name+".dll");return File.Exists(p)?Assembly.LoadFrom(p):null;};
var mod=Assembly.LoadFrom(Path.GetFullPath("../../../Packages/Overhaul/Overhaul.dll"));var type=mod.GetType("Auga.ConstructionRowScroll");var flags=BindingFlags.Static|BindingFlags.NonPublic;
var host=new GameObject("Inactive construction check");host.SetActive(false);var root=UnityEngine.Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/OverhaulBuild/AugaConstruction.prefab"),host.transform);var ui=root.GetComponent<BuildUi>();var scroll=ui.m_pieceScrollRect;var previous=scroll.scrollSensitivity;object[] args={scroll,0f};type.GetMethod("Prefix",flags).Invoke(null,args);float row=scroll.scrollSensitivity;if(row!=1440f)throw new Exception("Expected row pitch 72 times wheel correction 20, got "+row);type.GetMethod("Finalizer",flags).Invoke(null,new object[]{scroll,args[1]});if(scroll.scrollSensitivity!=previous)throw new Exception("Sensitivity not restored");
var test=new GameObject("Scroll fixture",typeof(RectTransform),typeof(ScrollRect));var rect=test.GetComponent<RectTransform>();rect.sizeDelta=new Vector2(400,200);var sc=test.GetComponent<ScrollRect>();var content=new GameObject("Content",typeof(RectTransform)).GetComponent<RectTransform>();content.SetParent(rect,false);content.anchorMin=new Vector2(0,1);content.anchorMax=new Vector2(1,1);content.pivot=new Vector2(.5f,1);content.sizeDelta=new Vector2(0,1000);sc.content=content;sc.viewport=rect;sc.horizontal=false;sc.movementType=ScrollRect.MovementType.Clamped;sc.scrollSensitivity=row;Canvas.ForceUpdateCanvases();
var events=new GameObject("Events",typeof(EventSystem));var data=new PointerEventData(events.GetComponent<EventSystem>());data.scrollDelta=new Vector2(0,-0.05f);sc.OnScroll(data);if(Mathf.Abs(content.anchoredPosition.y-72)>0.01f)throw new Exception("One notch mismatch "+content.anchoredPosition);data.scrollDelta=new Vector2(0,0.05f);sc.OnScroll(data);if(Mathf.Abs(content.anchoredPosition.y)>0.01f)throw new Exception("Reverse mismatch");
File.WriteAllText("../../../Tools/AugaWork/construction-scroll-checks.txt","PASS actual construction prefab row pitch 72 with 20x wheel correction\nPASS temporary sensitivity restored\nPASS ScrollRect delta 0.05 moves one item row down and one row up\n");UnityEngine.Object.DestroyImmediate(test);UnityEngine.Object.DestroyImmediate(events);UnityEngine.Object.DestroyImmediate(host);
}}