using System.Linq;using System;using System.IO;using System.Reflection;using UnityEngine;
public class EncumberedPlayerFixture : Player { public bool AttackGate,DodgeGate,BuildGate;public override bool IsEncumbered()=>true;public override bool InAttack()=>AttackGate;public override bool InDodge()=>DodgeGate;public override bool InPlaceMode()=>BuildGate;public override bool InMinorAction()=>false; }
public class EncumberedNpcFixture : Humanoid {public override bool IsEncumbered()=>true;}
public static class EncumberedBlockCheck {
public static void Run(){const BindingFlags F=BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Static|BindingFlags.Instance;AppDomain.CurrentDomain.AssemblyResolve+=(s,a)=>{var p=Path.GetFullPath("../../../Libs/"+new AssemblyName(a.Name).Name+".dll");return File.Exists(p)?Assembly.LoadFrom(p):null;};var mod=Assembly.LoadFrom(Path.GetFullPath("../../../Packages/Overhaul/Overhaul.dll"));var root=new GameObject("Inactive fixtures");root.SetActive(false);var player=root.AddComponent<EncumberedPlayerFixture>();player.m_nview=root.AddComponent<ZNetView>();player.m_animator=root.AddComponent<Animator>();player.m_blocking=true;int n=0;Action<bool,string> Check=(b,s)=>{if(!b)throw new Exception(s);n++;};Check(!player.IsBlocking(),"Reproduced native encumbrance veto");
var ha=Assembly.LoadFrom(Path.GetFullPath("../../../Libs/0Harmony.dll"));var ht=ha.GetType("HarmonyLib.Harmony");var hm=ha.GetType("HarmonyLib.HarmonyMethod");var harmony=Activator.CreateInstance(ht,new object[]{"overhaul.encumbered.block.check"});var patch=ht.GetMethods().First(m=>m.Name=="Patch" && m.GetParameters().Length>=5 && m.GetParameters()[0].ParameterType==typeof(MethodBase));var args=new object[patch.GetParameters().Length];args[0]=typeof(Humanoid).GetMethod("IsBlocking");args[3]=Activator.CreateInstance(hm,new object[]{mod.GetType("Overhaul.Patches.HumanoidPatches").GetMethod("IsBlocking_Transpiler",F)});patch.Invoke(harmony,args);
try{Check(player.IsBlocking(),"Encumbered player can enter guard");player.m_blocking=false;Check(!player.IsBlocking(),"Release exits guard while encumbered");player.m_blocking=true;player.AttackGate=true;Check(!player.IsBlocking(),"Attack restriction retained");player.AttackGate=false;player.DodgeGate=true;Check(!player.IsBlocking(),"Dodge restriction retained");player.DodgeGate=false;player.BuildGate=true;Check(!player.IsBlocking(),"Building restriction retained");player.BuildGate=false;Check(player.IsBlocking(),"Guard available again");var npcObject=new GameObject("NPC");npcObject.SetActive(false);var npc=npcObject.AddComponent<EncumberedNpcFixture>();npc.m_nview=npcObject.AddComponent<ZNetView>();npc.m_blocking=true;Check(!npc.IsBlocking(),"NPC behavior unchanged");File.WriteAllText("../../../Tools/AugaWork/encumbered-block-check.txt","PASS "+n+" native/patched runtime checks. "+mod.GetName().Version);}finally{ht.GetMethod("UnpatchSelf").Invoke(harmony,null);}
}}

