using System;using System.IO;using System.Reflection;using System.Linq;using System.Collections.Generic;using System.Runtime.Serialization;using UnityEngine;using UnityEngine.EventSystems;using UnityEditor;using Object=UnityEngine.Object;
public static class OverhaulBuildLifecycleCheck {
const BindingFlags F=BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Static|BindingFlags.Instance;
[InitializeOnLoadMethod] static void Install(){EditorApplication.playModeStateChanged+=Changed;} public static void Begin(){UnityEditor.SceneManagement.EditorSceneManager.NewScene(UnityEditor.SceneManagement.NewSceneSetup.EmptyScene,UnityEditor.SceneManagement.NewSceneMode.Single);SessionState.SetBool("BuildLifecycle",true);EditorApplication.EnterPlaymode();}
static void Changed(PlayModeStateChange state){if(state!=PlayModeStateChange.EnteredPlayMode||!SessionState.GetBool("BuildLifecycle",false))return;SessionState.SetBool("BuildLifecycle",false);EditorApplication.playModeStateChanged-=Changed;try{Run();File.WriteAllText("../../../Tools/AugaWork/construction-lifecycle.txt","PASS packaged category fonts, native icon material, recent/usage grid offsets, prefab replacement, author window and child references survive old panel destruction, native UpdateCrosshair at rest and bow draw, favourites save/load and Close before hidden HUD activation.");EditorApplication.Exit(0);}catch(Exception e){File.WriteAllText("../../../Tools/AugaWork/construction-lifecycle.txt","FAIL "+e);Debug.LogException(e);EditorApplication.Exit(1);}}
static void Run(){
var loc=(Localization)FormatterServices.GetUninitializedObject(typeof(Localization));foreach(var f in typeof(Localization).GetFields(F).Where(f=>!f.IsStatic)){if(f.FieldType==typeof(char[]))f.SetValue(loc," (){}[]+-!?/\\&%,.:-=<>\n".ToCharArray());else if(f.FieldType==typeof(System.Text.StringBuilder))f.SetValue(loc,new System.Text.StringBuilder());else if(f.FieldType.IsGenericType&&(f.FieldType.GetGenericTypeDefinition()==typeof(Dictionary<,>)||f.FieldType.GetGenericTypeDefinition()==typeof(List<>)))f.SetValue(loc,Activator.CreateInstance(f.FieldType));else if(f.Name=="m_cache")f.SetValue(loc,Activator.CreateInstance(f.FieldType,new object[]{100}));}typeof(Localization).GetField("m_instance",F).SetValue(null,loc);

AppDomain.CurrentDomain.AssemblyResolve+=(s,a)=>{var p=Path.GetFullPath("../../../Libs/"+new AssemblyName(a.Name).Name+".dll");return File.Exists(p)?Assembly.LoadFrom(p):null;};
UnityEngine.InputSystem.EnhancedTouch.EnhancedTouchSupport.Enable();var input=FormatterServices.GetUninitializedObject(typeof(ZInput));foreach(var f in typeof(ZInput).GetFields(F).Where(f=>!f.IsStatic&&f.FieldType.IsGenericType&&f.FieldType.GetGenericTypeDefinition()==typeof(Dictionary<,>)))f.SetValue(input,Activator.CreateInstance(f.FieldType));typeof(ZInput).GetField("m_instance",F).SetValue(null,input);var plugin=Assembly.LoadFrom(Path.GetFullPath("../../../Packages/Overhaul/Overhaul.dll"));plugin.GetType("Overhaul.IntegratedUi").GetMethod("LoadDependencies",F).Invoke(null,null);
var auga=plugin.GetType("Auga.Auga");var field=auga.GetField("Assets",F);var assets=field.GetValue(null);if(assets==null){assets=Activator.CreateInstance(field.FieldType);field.SetValue(null,assets);}AssetBundle bundle;using(var stream=plugin.GetManifestResourceStream("Overhaul.augaassets"))using(var buffer=new MemoryStream()){stream.CopyTo(buffer);bundle=AssetBundle.LoadFromMemory(buffer.ToArray());}field.FieldType.GetField("Construction").SetValue(assets,bundle.LoadAsset<GameObject>("AugaConstruction"));field.FieldType.GetField("Hud").SetValue(assets,bundle.LoadAsset<GameObject>("HUD"));
var host=new GameObject("Hidden HUD test");host.SetActive(false);var eventSystem=new GameObject("Events",typeof(EventSystem));var original=OverhaulBuildSource.Load().LoadAsset<GameObject>("Assets/UI/prefabs/IngameGui/IngameGui_HUD.prefab");var hudObject=Object.Instantiate(original,host.transform);var hud=hudObject.GetComponent<Hud>();Hud.m_instance=hud;var old=hud.m_buildUi;var iconMaterial=old.m_pieceButtonPrefab.GetComponent<BuildUiPieceButton>().m_icon.material;var oldPanel=hud.m_buildHud;var author=hud.m_hoveredPieceAuthorWindow;Debug.Log("Author window path: "+AnimationUtility.CalculateTransformPath(author.transform,hud.transform));
plugin.GetType("Auga.Construction_Setup").GetMethod("Postfix",F).Invoke(null,new object[]{hud});Object.DestroyImmediate(oldPanel);if(!hud.m_hoveredPieceAuthorWindow || hud.m_hoveredPieceAuthorWindow!=author)throw new Exception("Construction destroyed the author window used by UpdateCrosshair");hud.m_hoveredPieceAuthorWindow.SetActive(false);if(!hud.m_hoveredPieceAuthorName||!hud.m_hoveredPieceAuthorPlatformUserId||!hud.m_hoveredPieceAuthorProfilePic)throw new Exception("Author window children lost");var playerObject=new GameObject("Crosshair player");playerObject.transform.SetParent(host.transform);var player=playerObject.AddComponent<Player>();hud.UpdateCrosshair(player,0f);hud.UpdateCrosshair(player,0.5f);if(!hud.m_crosshairBow.gameObject.activeSelf)throw new Exception("Bow crosshair failed");if(hud.m_buildUi==old)throw new Exception("Native fallback used unexpectedly");var ui=hud.m_buildUi;if(ui.m_pieceButtonPrefab.GetComponent<BuildUiPieceButton>().m_icon.material!=iconMaterial)throw new Exception("Native icon material missing");foreach(var text in ui.m_tagButtonPrefab.GetComponentsInChildren<TMPro.TMP_Text>(true))if(!text.font)throw new Exception("Category font missing from packaged bundle");ui.SetTagListActive(false,true);if(Mathf.Abs(ui.m_pieceView.offsetMin.x)>.01f)throw new Exception("Recent grid offset");ui.SetTagListActive(true,true);if(Mathf.Abs(ui.m_pieceView.offsetMin.x-280f)>.01f)throw new Exception("Usage grid offset");if(ui.m_favoritePieceList==null||ui.m_recentPieceList==null)throw new Exception("Lists uninitialized");ui.m_favoritePieceList.AddPiece("woodwall");ui.AddRecentPiece(original.GetComponent<Piece>());var bytes=ui.SaveToBinary();ui.LoadFromBinary(bytes);if(!ui.m_favoritePieceList.IsFavorite("woodwall"))throw new Exception("Favourite lost");ui.Close();ui.LoadFromBinary(new byte[0]);ui.Close();if(ui.gameObject.activeSelf)throw new Exception("Close failed");
}
}
