using UnityEngine.EventSystems;using System;using System.IO;using System.Linq;using System.Reflection;using System.Runtime.Serialization;using System.Collections.Generic;using UnityEngine;using UnityEngine.UI;using TMPro;using UnityEditor;using Object=UnityEngine.Object;
public static class OverhaulBuildRuntimePreview {
const BindingFlags F=BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance|BindingFlags.Static;
static Sprite Icon(Sprite original){foreach(var b in OverhaulBuildSource.Bundles)foreach(var n in b.GetAllAssetNames().Where(n=>n.EndsWith(".spriteatlas"))){var atlas=b.LoadAsset<UnityEngine.U2D.SpriteAtlas>(n);var sprite=atlas.GetSprite(original.name);if(!sprite)continue;var entries=(Newtonsoft.Json.Linq.JArray)Newtonsoft.Json.Linq.JObject.Parse(EditorJsonUtility.ToJson(atlas))["SpriteAtlas"]["m_RenderDataMap"];var key=Newtonsoft.Json.Linq.JObject.Parse(EditorJsonUtility.ToJson(sprite))["Sprite"]["m_RenderDataKey"]["first"].ToString();int index=Enumerable.Range(0,entries.Count).First(i=>entries[i]["first"]["first"].ToString()==key);var r=entries[index]["second"]["textureRect"];var texture=(Texture2D)new SerializedObject(atlas).FindProperty("m_RenderDataMap").GetArrayElementAtIndex(index).FindPropertyRelative("second.texture").objectReferenceValue;return Sprite.Create(texture,new Rect((float)r["x"],(float)r["y"],(float)r["width"],(float)r["height"]),new Vector2(.5f,.5f),100);}return original;}
public static void ValidateAndCapture(){OverhaulBuildChecks.Run();Run();} public static void Run(){var loc=(Localization)FormatterServices.GetUninitializedObject(typeof(Localization));foreach(var f in typeof(Localization).GetFields(F).Where(f=>!f.IsStatic)){if(f.FieldType==typeof(char[]))f.SetValue(loc," (){}[]+-!?/\\&%,.:-=<>\n".ToCharArray());else if(f.FieldType==typeof(System.Text.StringBuilder))f.SetValue(loc,new System.Text.StringBuilder());else if(f.FieldType.IsGenericType&&(f.FieldType.GetGenericTypeDefinition()==typeof(Dictionary<,>)||f.FieldType.GetGenericTypeDefinition()==typeof(List<>)))f.SetValue(loc,Activator.CreateInstance(f.FieldType));else if(f.Name=="m_cache")f.SetValue(loc,Activator.CreateInstance(f.FieldType,new object[]{100}));}typeof(Localization).GetField("m_instance",F).SetValue(null,loc);

foreach(var pair in Newtonsoft.Json.JsonConvert.DeserializeObject<Dictionary<string,string>>(File.ReadAllText("../../../Overhaul/Overhaul/Distribution/Localisation/translationsFR.json")))loc.AddWord(pair.Key,pair.Value);
var tags=new[]{"misc:Divers","crafting:Fabrication","building:Construction","floor:Sol","wall:Mur","roof:Toit","architecture:Architecture","furniture:Meubles","lighting:Lumière","decor:Décoration","storage:Stockage","transport:Transport","food:Nourriture","mead:Hydromels","feasts:Festins","defense:Défenses","stacks:Piles","stairs:Escaliers","doors:Portes","seasonal:Saisonnier"};
foreach(var tag in tags){var pair=tag.Split(':');loc.AddWord("tag_"+pair[0],pair[1]);}
loc.AddWord("menu_filter","Filtre");loc.AddWord("hud_all","Tout montrer");loc.AddWord("hud_filter","Filtre");loc.AddWord("hud_addfavoritecategory","Ajouter une catégorie");
var host=new GameObject("Inactive runtime preview");host.SetActive(false);var events=new GameObject("Events",typeof(EventSystem));
var root=Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/OverhaulBuild/AugaConstruction.prefab"),host.transform);var ui=root.GetComponent<BuildUi>();
var native=OverhaulBuildSource.Load().LoadAsset<GameObject>("Assets/UI/prefabs/IngameGui/IngameGui_HUD.prefab").GetComponent<Hud>().m_buildUi;
ui.m_pieceButtonPrefab.GetComponent<BuildUiPieceButton>().m_icon.material=native.m_pieceButtonPrefab.GetComponent<BuildUiPieceButton>().m_icon.material;
ui.m_recentPieceList=new RecentPieceList("Recent",150);ui.m_favoritePieceList=new FavoritePieceList("Favorites");ui.m_pieceLists.Add(new ByUsagePieceList("Usage"));ui.m_pieceLists.Add(new ByMaterialPieceList("Material",ui.m_majorMaterials));ui.m_pieceLists.Add(ui.m_recentPieceList);ui.m_pieceLists.Add(ui.m_favoritePieceList);ui.m_addFavoriteTagButton=Object.Instantiate(ui.m_tagButtonPrefab,ui.m_tagListScrollContent).GetComponent<BuildUiTagButton>();ui.m_tabButtons.AddRange(ui.m_tabContainer.GetComponentsInChildren<Button>(true));ui.m_tagListOpenOffset=ui.m_pieceView.offsetMin.x;
var tableObject=new GameObject("Fixture table");tableObject.SetActive(false);var table=tableObject.AddComponent<PieceTable>();ui.m_currentBuildTool=table;
var pieces=OverhaulBuildSource.Bundles.SelectMany(b=>b.GetAllAssetNames().Where(n=>n.EndsWith(".prefab")&&n.IndexOf("/Pieces/",StringComparison.OrdinalIgnoreCase)>=0).Select(n=>b.LoadAsset<GameObject>(n))).Where(p=>p&&p.GetComponent<Piece>()&&p.GetComponent<Piece>().m_icon).Select(p=>p.GetComponent<Piece>()).ToArray();
pieces=pieces.Take(70).Concat(pieces.Where(p=>p.m_repairPiece)).Distinct().ToArray();
foreach(var piece in pieces){table.m_availablePieces.Add(piece);ui.AddRecentPiece(piece);}
ui.m_showAllTagsButton.Setup("$hud_all",-1,false);ui.m_debugUi.gameObject.SetActive(false);ui.m_favoritesDropdown.gameObject.SetActive(false);root.transform.Find("Controls/FavoritesBackgroundClick").gameObject.SetActive(false);
foreach(var hint in root.GetComponentsInChildren<UIInputHint>(true))hint.gameObject.SetActive(false);
foreach(var text in root.GetComponentsInChildren<TMP_Text>(true))if(!text.text.Contains("$KEY"))text.text=loc.Localize(text.text);
foreach(var tab in new[]{0,2,0}) {
ui.SelectPieceList(tab);
if(Mathf.Abs(ui.m_pieceView.offsetMin.x-(tab==2?0:280))>.01f)throw new Exception("Incorrect grid offset after native tab switch");
if(ui.m_tagButtons.Any(t=>t.m_textMeshes.Any(text=>!text.font)))throw new Exception("Missing category font");
foreach(var button in ui.m_pieceButtons)button.m_icon.sprite=Icon(button.Piece.m_icon);
if(ui.m_specialPieceButton)ui.m_specialPieceButton.m_icon.sprite=Icon(ui.m_specialPieceButton.Piece.m_icon);
Capture(root,tab==2?"recent-runtime":"usage-runtime");
}
Object.DestroyImmediate(root);Object.DestroyImmediate(tableObject);Object.DestroyImmediate(events);Object.DestroyImmediate(host);
}
static void Capture(GameObject root,string name){var canvasObj=new GameObject("Canvas",typeof(Canvas));var cameraObj=new GameObject("Camera",typeof(Camera));var camera=cameraObj.GetComponent<Camera>();camera.orthographic=true;camera.orthographicSize=410;camera.transform.position=new Vector3(0,0,-10);camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=new Color(.065f,.075f,.08f);camera.cullingMask=1<<30;var canvas=canvasObj.GetComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=camera;canvas.planeDistance=1;canvas.referencePixelsPerUnit=50;canvasObj.layer=30;
var rt=new RenderTexture(1280,820,24);camera.targetTexture=rt;root.transform.SetParent(canvasObj.transform,false);foreach(var t in root.GetComponentsInChildren<Transform>(true))t.gameObject.layer=30;root.SetActive(true);root.transform.localPosition=Vector3.zero;foreach(var n in new[]{"Controls","Controls/bar","Controls/bar/SelectionWindow","Controls/bar/SelectionWindow/Main View","Controls/bar/SelectionWindow/Main View/Root"})root.transform.Find(n).gameObject.SetActive(true);foreach(var text in root.GetComponentsInChildren<TMP_Text>(true))if(!text.text.Contains("$KEY"))text.text=Localization.instance.Localize(text.text);Canvas.ForceUpdateCanvases();LayoutRebuilder.ForceRebuildLayoutImmediate((RectTransform)root.transform);Canvas.ForceUpdateCanvases();File.WriteAllLines("../../../Tools/AugaWork/build-geometry.txt",root.GetComponentsInChildren<RectTransform>(true).Select(r=>r.name+" active="+r.gameObject.activeInHierarchy+" rect="+r.rect+" pos="+r.position+" scale="+r.lossyScale));foreach(var fitter in root.GetComponentsInChildren<AugaUnity.HorizontalDividerFitter>(true))fitter.LateUpdate();camera.Render();RenderTexture.active=rt;var texture=new Texture2D(1280,820,TextureFormat.RGB24,false);texture.ReadPixels(new Rect(0,0,1280,820),0,0);texture.Apply();File.WriteAllBytes("../../../Tools/AugaWork/construction-"+name+".png",texture.EncodeToPNG());RenderTexture.active=null;root.transform.SetParent(null,false);root.SetActive(false);Object.DestroyImmediate(canvasObj);Object.DestroyImmediate(cameraObj);Object.DestroyImmediate(rt);Object.DestroyImmediate(texture);}
}
