using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using System.Runtime.Serialization;using UnityEngine;using UnityEngine.EventSystems;using UnityEditor;using Object=UnityEngine.Object;
public static class OverhaulBuildChecks {
const BindingFlags F=BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Static|BindingFlags.Instance;static List<string> checks=new List<string>();static void Check(bool ok,string text){if(!ok)throw new Exception(text);checks.Add("PASS "+text);}static void Call(object o,string n,params object[] args){o.GetType().GetMethod(n,F).Invoke(o,args);}
public static void Run(){var loc=(Localization)FormatterServices.GetUninitializedObject(typeof(Localization));foreach(var f in typeof(Localization).GetFields(F).Where(f=>!f.IsStatic)){if(f.FieldType==typeof(char[]))f.SetValue(loc," (){}[]+-!?/\\&%,.:-=<>\n".ToCharArray());else if(f.FieldType==typeof(System.Text.StringBuilder))f.SetValue(loc,new System.Text.StringBuilder());else if(f.FieldType.IsGenericType&&(f.FieldType.GetGenericTypeDefinition()==typeof(Dictionary<,>)||f.FieldType.GetGenericTypeDefinition()==typeof(List<>)))f.SetValue(loc,Activator.CreateInstance(f.FieldType));else if(f.Name=="m_cache")f.SetValue(loc,Activator.CreateInstance(f.FieldType,new object[]{100}));}typeof(Localization).GetField("m_instance",F).SetValue(null,loc);
var host=new GameObject("Inactive tests");host.SetActive(false);var events=new GameObject("Events",typeof(EventSystem));var root=Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/OverhaulBuild/AugaConstruction.prefab"),host.transform);var ui=root.GetComponent<BuildUi>();
foreach(var t in root.GetComponentsInChildren<Transform>(true))Check(GameObjectUtility.GetMonoBehavioursWithMissingScriptCount(t.gameObject)==0,"scripts "+t.name);
// Same list initialization as native Awake, without starting the game's singleton-dependent Update loop.
ui.m_recentPieceList=new RecentPieceList("Recent",150);ui.m_favoritePieceList=new FavoritePieceList("Favorites");ui.m_pieceLists.Add(new ByUsagePieceList("Usage"));ui.m_pieceLists.Add(new ByMaterialPieceList("Material",ui.m_majorMaterials));ui.m_pieceLists.Add(ui.m_recentPieceList);ui.m_pieceLists.Add(ui.m_favoritePieceList);ui.m_addFavoriteTagButton=Object.Instantiate(ui.m_tagButtonPrefab,ui.m_tagListScrollContent).GetComponent<BuildUiTagButton>();ui.m_tabButtons.AddRange(ui.m_tabContainer.GetComponentsInChildren<UnityEngine.UI.Button>(true));ui.m_tagListOpenOffset=ui.m_pieceView.offsetMin.x;
var tableObject=new GameObject("table");tableObject.SetActive(false);var table=tableObject.AddComponent<PieceTable>();ui.m_currentBuildTool=table;
foreach(var name in new[]{"Mur en bois","Sol en pierre"}){var g=new GameObject(name);g.transform.SetParent(host.transform);var p=g.AddComponent<Piece>();p.m_name=name;p.m_resources=new Piece.Requirement[0];p.m_usage=(Piece.UsageTagFlags)1;table.m_availablePieces.Add(p);}
var repairObject=new GameObject("repair");repairObject.transform.SetParent(host.transform);var repair=repairObject.AddComponent<Piece>();repair.m_name="Reparer";repair.m_repairPiece=true;repair.m_resources=new Piece.Requirement[0];table.m_availablePieces.Add(repair);ui.m_showAllTagsButton.Setup("Tout",-1,false);ui.SelectPieceList(0);Check(ui.m_pieceButtons.Count==2,"usage lists all available pieces");Check(ui.m_specialPieceButton&&ui.m_specialPieceButton.Piece==repair&&ui.m_specialButtonsContainer.gameObject.activeSelf,"repair tool remains available separately from construction pieces");Call(ui,"SetCurrentTag",-1,false);ui.m_searchField.text="bois";Call(ui,"UpdateSearch","bois");Check(ui.m_pieceButtons.Count(p=>p.gameObject.activeSelf)==1,"native search filters French piece names");ui.m_searchField.text="";Call(ui,"UpdateSearch","");Check(ui.m_pieceButtons.Count(p=>p.gameObject.activeSelf)==2,"clearing search restores pieces");ui.SelectPieceList(1);Check(ui.m_currentPieceList==1,"material tab invokes native material grouping");var chosen=table.m_availablePieces.First();ui.AddRecentPiece(chosen);ui.SelectPieceList(2);Check(ui.m_pieceButtons.Count==1,"recent tab lists placed piece");ui.m_favoritePieceList.AddPiece(chosen.gameObject.name);ui.SelectPieceList(3);Check(ui.IsFavoritePiece(chosen)&&ui.m_pieceButtons.Count==1,"favorite tab filters favorites");var bytes=ui.SaveToBinary();ui.m_favoritePieceList=new FavoritePieceList("Favorites");ui.m_recentPieceList=new RecentPieceList("Recent",150);ui.LoadFromBinary(bytes);Check(ui.IsFavoritePiece(chosen),"favorites persist in native character format");ui.ConfigureButtonNavigation();File.WriteAllLines("../../../Tools/AugaWork/construction-checks.txt",checks);Object.DestroyImmediate(root);Object.DestroyImmediate(host);Object.DestroyImmediate(tableObject);Object.DestroyImmediate(events);}
}




