using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEngine.UI;using TMPro;using UnityEditor;using Object=UnityEngine.Object;
public static class OverhaulBuildPreview {
static Sprite Icon(Sprite original){foreach(var b in OverhaulBuildSource.Bundles)foreach(var n in b.GetAllAssetNames().Where(n=>n.EndsWith(".spriteatlas"))){var atlas=b.LoadAsset<UnityEngine.U2D.SpriteAtlas>(n);var sprite=atlas.GetSprite(original.name);if(!sprite)continue;var entries=(Newtonsoft.Json.Linq.JArray)Newtonsoft.Json.Linq.JObject.Parse(EditorJsonUtility.ToJson(atlas))["SpriteAtlas"]["m_RenderDataMap"];var key=Newtonsoft.Json.Linq.JObject.Parse(EditorJsonUtility.ToJson(sprite))["Sprite"]["m_RenderDataKey"]["first"].ToString();int index=Enumerable.Range(0,entries.Count).First(i=>entries[i]["first"]["first"].ToString()==key);var r=entries[index]["second"]["textureRect"];var texture=(Texture2D)new SerializedObject(atlas).FindProperty("m_RenderDataMap").GetArrayElementAtIndex(index).FindPropertyRelative("second.texture").objectReferenceValue;return Sprite.Create(texture,new Rect((float)r["x"],(float)r["y"],(float)r["width"],(float)r["height"]),new Vector2(.5f,.5f),100);}return original;}
public static void Run(){var host=new GameObject("Inactive preview");host.SetActive(false);var root=Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/OverhaulBuild/AugaConstruction.prefab"),host.transform);var ui=root.GetComponent<BuildUi>();var report=new List<string>();foreach(var f in typeof(BuildUi).GetFields(System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.Public|System.Reflection.BindingFlags.NonPublic).Where(f=>f.IsDefined(typeof(SerializeField),false)&&typeof(Object).IsAssignableFrom(f.FieldType))){var v=f.GetValue(ui) as Object;if(!v)throw new Exception("Missing BuildUi reference "+f.Name);report.Add("PASS "+f.Name);}if(ui.m_tabContainer.childCount!=4)throw new Exception("Tab count");
var labels=new[]{"USAGE","MATÉRIAUX","RÉCENTS","FAVORIS"};int index=0;foreach(Transform t in ui.m_tabContainer){foreach(var text in t.GetComponentsInChildren<TMP_Text>(true))text.text=labels[index];t.Find("Selected").gameObject.SetActive(index==0);index++;}
var categories=new[]{"Tout","Construction en bois","Construction en pierre","Artisanat","Mobilier","Décoration","Défenses"};ui.m_showAllTagsButton.m_toggledOnObject.SetActive(true);foreach(var text in ui.m_showAllTagsButton.GetComponentsInChildren<TMP_Text>(true))text.text="Tout";
for(int i=1;i<categories.Length;i++){var t=Object.Instantiate(ui.m_tagButtonPrefab,ui.m_tagListScrollContent);foreach(var text in t.GetComponentsInChildren<TMP_Text>(true))text.text=categories[i];t.GetComponent<BuildUiTagButton>().m_toggledOnObject.SetActive(false);t.SetActive(true);}
ui.m_materialSeparator.gameObject.SetActive(false);ui.m_searchField.text="";if(ui.m_searchField.placeholder is TMP_Text placeholder)placeholder.text="Rechercher…";if(ui.m_searchField.placeholder is UnityEngine.UI.Text legacyPlaceholder)legacyPlaceholder.text="Rechercher...";ui.m_debugUi.gameObject.SetActive(false);ui.m_favoritesDropdown.gameObject.SetActive(false);root.transform.Find("Controls/FavoritesBackgroundClick").gameObject.SetActive(false);
var bundle=OverhaulBuildSource.Load();var pieces=OverhaulBuildSource.Bundles.SelectMany(b=>b.GetAllAssetNames().Select(n=>new{b,n})).Where(x=>x.n.EndsWith(".prefab")&&x.n.IndexOf("/Pieces/",StringComparison.OrdinalIgnoreCase)>=0).Select(x=>x.b.LoadAsset<GameObject>(x.n)).Where(p=>p&&p.GetComponent<Piece>()&&p.GetComponent<Piece>().m_icon).Take(54).ToArray();var unused=bundle.GetAllAssetNames().Where(n=>n.EndsWith(".prefab")&&n.IndexOf("/Pieces/",StringComparison.OrdinalIgnoreCase)>=0).Select(n=>bundle.LoadAsset<GameObject>(n)).Where(p=>p&&p.GetComponent<Piece>()&&p.GetComponent<Piece>().m_icon).Take(54).ToArray();
var repair=OverhaulBuildSource.Bundles.SelectMany(b=>b.GetAllAssetNames().Where(n=>n.EndsWith(".prefab")&&n.IndexOf("/Pieces/",StringComparison.OrdinalIgnoreCase)>=0).Select(n=>b.LoadAsset<GameObject>(n))).Where(p=>p&&p.GetComponent<Piece>()).First(p=>p.GetComponent<Piece>().m_repairPiece);var repairButton=Object.Instantiate(ui.m_pieceButtonPrefab,ui.m_specialButtonsContainer);var repairControl=repairButton.GetComponent<BuildUiPieceButton>();repairControl.m_icon.sprite=Icon(repair.GetComponent<Piece>().m_icon);repairControl.m_icon.color=Color.white;repairControl.m_upgradeArrow.gameObject.SetActive(false);repairControl.m_favoriteStar.gameObject.SetActive(false);repairButton.SetActive(true);ui.m_specialButtonsContainer.gameObject.SetActive(true);
for(int i=0;i<pieces.Length;i++){var p=Object.Instantiate(ui.m_pieceButtonPrefab,ui.m_pieceButtonsContainer);var c=p.GetComponent<BuildUiPieceButton>();c.m_icon.sprite=Icon(pieces[i].GetComponent<Piece>().m_icon);c.m_icon.color=Color.white;c.m_upgradeArrow.gameObject.SetActive(false);c.m_favoriteStar.gameObject.SetActive(i==3);p.SetActive(true);}
foreach(var hint in root.GetComponentsInChildren<UIInputHint>(true))hint.gameObject.SetActive(false);
// Static rendering of the real prefab; no simulated click handlers.
foreach(var c in root.GetComponentsInChildren<MonoBehaviour>(true))if(!(c is Graphic)&&!(c is LayoutGroup)&&!(c is ContentSizeFitter)&&!(c is LayoutElement)&&!(c is Mask)&&!(c is RectMask2D)&&!(c is ScrollRect)&&!(c is Scrollbar)&&c.GetType().Name!="HorizontalDividerFitter"&&c.GetType().Name!="UIGradient")Object.DestroyImmediate(c);
var canvasObj=new GameObject("Canvas",typeof(Canvas));var cameraObj=new GameObject("Camera",typeof(Camera));var camera=cameraObj.GetComponent<Camera>();camera.orthographic=true;camera.orthographicSize=410;camera.transform.position=new Vector3(0,0,-10);camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=new Color(.065f,.075f,.08f);camera.cullingMask=1<<30;var canvas=canvasObj.GetComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=camera;canvas.planeDistance=1;canvas.referencePixelsPerUnit=50;canvasObj.layer=30;
var rt=new RenderTexture(1280,820,24);camera.targetTexture=rt;root.transform.SetParent(canvasObj.transform,false);foreach(var t in root.GetComponentsInChildren<Transform>(true))t.gameObject.layer=30;root.SetActive(true);root.transform.localPosition=Vector3.zero;foreach(var n in new[]{"Controls","Controls/bar","Controls/bar/SelectionWindow","Controls/bar/SelectionWindow/Main View","Controls/bar/SelectionWindow/Main View/Root"})root.transform.Find(n).gameObject.SetActive(true);Canvas.ForceUpdateCanvases();LayoutRebuilder.ForceRebuildLayoutImmediate((RectTransform)root.transform);Canvas.ForceUpdateCanvases();File.WriteAllLines("../../../Tools/AugaWork/build-geometry.txt",root.GetComponentsInChildren<RectTransform>(true).Select(r=>r.name+" active="+r.gameObject.activeInHierarchy+" rect="+r.rect+" pos="+r.position+" scale="+r.lossyScale));foreach(var fitter in root.GetComponentsInChildren<AugaUnity.HorizontalDividerFitter>(true))fitter.LateUpdate();camera.Render();RenderTexture.active=rt;var texture=new Texture2D(1280,820,TextureFormat.RGB24,false);texture.ReadPixels(new Rect(0,0,1280,820),0,0);texture.Apply();File.WriteAllBytes("../../../Tools/AugaWork/construction-preview.png",texture.EncodeToPNG());RenderTexture.active=null;File.WriteAllLines("../../../Tools/AugaWork/construction-contract.txt",report);Object.DestroyImmediate(canvasObj);Object.DestroyImmediate(cameraObj);Object.DestroyImmediate(host);Object.DestroyImmediate(rt);Object.DestroyImmediate(texture);}
}



