using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
public static class PlantEasilyChecks {
const string Root="D:/Valheim/valheim_Data/StreamingAssets/SoftRef/";
static Dictionary<string,List<string>> deps=new Dictionary<string,List<string>>();
static Dictionary<string,AssetBundle> bundles=new Dictionary<string,AssetBundle>();
static void Load(string id){if(bundles.ContainsKey(id))return;bundles[id]=null;if(deps.ContainsKey(id))foreach(var d in deps[id])Load(d);bundles[id]=AssetBundle.LoadFromFile(Root+"Bundles/"+id);}
public static void Run(){ AppDomain.CurrentDomain.AssemblyResolve+=(s,a)=>{var p=Path.GetFullPath("../../../Libs/"+new System.Reflection.AssemblyName(a.Name).Name+".dll");return File.Exists(p)?System.Reflection.Assembly.LoadFrom(p):null;};
var paths=new Dictionary<string,string>();string current=null,bundle=null;bool assets=false;
foreach(var line in File.ReadAllLines(Root+"manifest_extended").Concat(File.ReadAllLines(Root+"manifest"))){
if(line=="bundle dependencies:")assets=false;else if(line.StartsWith("asset locations:"))assets=true;
else if(!assets){if(line.StartsWith("- bundle: ")){current=line.Substring(10).Trim();deps[current]=new List<string>();}else if(current!=null&&line.StartsWith("  - "))deps[current].Add(line.Substring(4).Trim());}
else if(line.StartsWith("  bundle: "))bundle=line.Substring(10).Trim();else if(line.StartsWith("  path in bundle: "))paths[line.Substring(18).Trim()]=bundle;
}
var report=new List<string>();var f=System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.Public|System.Reflection.BindingFlags.NonPublic;
var mod=System.Reflection.Assembly.LoadFrom(Path.GetFullPath("../../../Packages/Overhaul/Overhaul.dll"));Func<string,Type> type=n=>mod.GetType("Advize_PlantEasily."+n,true);var bep=System.Reflection.Assembly.LoadFrom(Path.GetFullPath("../../../Libs/BepInEx.dll"));bep.GetType("BepInEx.Paths").GetMethod("SetExecutablePath",f).Invoke(null,new object[]{Path.GetFullPath("../../../Tools/AugaWork/plant-fixture/Test.exe"),null,null,new string[0]});var cfg=Activator.CreateInstance(bep.GetType("BepInEx.Configuration.ConfigFile"),new object[]{Path.GetFullPath("../../../Tools/AugaWork/plant-defaults.cfg"),false});var config=Activator.CreateInstance(type("ModConfig"),f,null,new[]{cfg},null);type("ModContext").GetField("config",f).SetValue(null,config);
var ht=System.Reflection.Assembly.LoadFrom(Path.GetFullPath("../../../Libs/0Harmony.dll")).GetType("HarmonyLib.Harmony");var harmony=Activator.CreateInstance(ht,new object[]{"overhaul.plant.checks"});
try{foreach(var t in mod.GetTypes().Where(t=>t.Namespace=="Advize_PlantEasily")){var processor=ht.GetMethod("CreateClassProcessor",new[]{typeof(Type)}).Invoke(harmony,new object[]{t});processor.GetType().GetMethod("Patch",Type.EmptyTypes).Invoke(processor,null);}report.Add("PASS all integrated Harmony patches install on current game DLL");}finally{ht.GetMethod("UnpatchSelf").Invoke(harmony,null);}
Func<string,GameObject> prefab=name=>{var p=paths.Single(x=>x.Key.EndsWith("/"+name+".prefab"));Load(p.Value);return bundles[p.Value].LoadAsset<GameObject>(p.Key);};var carrot=prefab("sapling_carrot");var turnip=prefab("sapling_turnip");var cultivator=prefab("Cultivator");
foreach(var plant in new[]{carrot,turnip}){float spacing=(float)type("ModUtils").GetMethod("GetPieceSpacing",f).Invoke(null,new object[]{plant});if(spacing<=plant.GetComponent<Plant>().m_growRadius)throw new Exception("Unsafe spacing");report.Add("PASS native "+plant.name+" spacing="+spacing);}
var host=new GameObject("Inactive plant fixtures");host.SetActive(false);var player=host.AddComponent<Player>();var old=Player.m_localPlayer;Player.m_localPlayer=player;player.m_rightItem=cultivator.GetComponent<ItemDrop>().m_itemData.Clone();if(!(bool)type("ModUtils").GetProperty("HoldingCultivator",f).GetValue(null))throw new Exception("Cultivator not recognized");player.m_rightItem=null;if((bool)type("ModUtils").GetProperty("HoldingCultivator",f).GetValue(null))throw new Exception("Empty hands accepted");report.Add("PASS cultivator scope and empty hands");
var grid=type("GhostGrid");foreach(var pair in new[]{new[]{1,1},new[]{2,2},new[]{3,4}}){type("ModConfig").GetProperty("Rows",f).SetValue(config,pair[0]);type("ModConfig").GetProperty("Columns",f).SetValue(config,pair[1]);int count=(int)grid.GetProperty("MaxActiveGhosts",f).GetValue(null);if(count!=pair[0]*pair[1]-1)throw new Exception("Grid count");report.Add("PASS grid "+pair[0]+"x"+pair[1]+" count="+(count+1));}
var state=type("PlacementState");state.GetField("BasePosition",f).SetValue(null,Vector3.zero);state.GetField("RowDirection",f).SetValue(null,new Vector3(0,0,2));state.GetField("ColumnDirection",f).SetValue(null,new Vector3(2,0,0));var pos=(Vector3)grid.GetMethod("GetGhostPosition",f).Invoke(null,new object[]{2,3,11});if(pos.x!=6||pos.z!=4)throw new Exception("Grid position");report.Add("PASS grid coordinates follow row and column spacing");
var rootGhost=UnityEngine.Object.Instantiate(carrot,host.transform);rootGhost.name=carrot.name;rootGhost.SetActive(false);grid.GetMethod("GrowPoolIfNeeded",f).Invoke(null,new object[]{rootGhost});var ghosts=(System.Collections.IList)grid.GetField("ExtraGhosts",f).GetValue(null);foreach(GameObject go in ghosts)go.transform.SetParent(host.transform,false);grid.GetMethod("BuildGrid",f).Invoke(null,new object[]{rootGhost});if(ghosts.Count!=11)throw new Exception("Actual ghost pool count");report.Add("PASS 3x4 native carrot ghost pool has 11 extra prefabs");
var all=new List<GameObject>{rootGhost};foreach(GameObject go in ghosts)all.Add(go);state.GetField("BasePosition",f).SetValue(null,Vector3.zero);state.GetField("BaseRotation",f).SetValue(null,Quaternion.identity);float pitch=(float)type("ModUtils").GetMethod("GetPieceSpacing",f).Invoke(null,new object[]{carrot});state.GetField("RowDirection",f).SetValue(null,Vector3.forward*pitch);state.GetField("ColumnDirection",f).SetValue(null,Vector3.right*pitch);
for(int i=0;i<all.Count;i++){var point=(Vector3)grid.GetMethod("GetGhostPosition",f).Invoke(null,new object[]{i/4,i%4,i});grid.GetMethod("UpdateGhostTransform",f).Invoke(null,new object[]{all[i],point});foreach(var behaviour in all[i].GetComponentsInChildren<MonoBehaviour>(true))UnityEngine.Object.DestroyImmediate(behaviour);foreach(var tr in all[i].GetComponentsInChildren<Transform>(true))tr.gameObject.layer=30;all[i].SetActive(true);}
var stage=new GameObject("Plant preview stage");foreach(var go in all)go.transform.SetParent(stage.transform,true);var cameraObject=new GameObject("Preview camera",typeof(Camera));var camera=cameraObject.GetComponent<Camera>();camera.transform.position=new Vector3(5,7,-6);camera.transform.LookAt(new Vector3(1.5f,0,1));camera.orthographic=true;camera.orthographicSize=3;camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=new Color(.07f,.085f,.065f);camera.cullingMask=1<<30;var lightObject=new GameObject("Light",typeof(Light));var light=lightObject.GetComponent<Light>();light.type=LightType.Directional;light.intensity=1.5f;light.transform.rotation=Quaternion.Euler(55,-30,0);RenderSettings.ambientLight=Color.gray;
var ground=GameObject.CreatePrimitive(PrimitiveType.Plane);ground.layer=30;ground.transform.position=new Vector3(1.5f,-.04f,1);ground.transform.localScale=Vector3.one;var mat=new Material(Shader.Find("Standard"));mat.color=new Color(.20f,.15f,.09f);ground.GetComponent<Renderer>().sharedMaterial=mat;
var rt=new RenderTexture(1000,700,24);camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var texture=new Texture2D(1000,700,TextureFormat.RGB24,false);texture.ReadPixels(new Rect(0,0,1000,700),0,0);texture.Apply();File.WriteAllBytes("../../../Tools/AugaWork/planteasily-grid-preview.png",texture.EncodeToPNG());RenderTexture.active=null;camera.targetTexture=null;UnityEngine.Object.DestroyImmediate(stage);UnityEngine.Object.DestroyImmediate(cameraObject);UnityEngine.Object.DestroyImmediate(lightObject);UnityEngine.Object.DestroyImmediate(ground);UnityEngine.Object.DestroyImmediate(mat);UnityEngine.Object.DestroyImmediate(texture);UnityEngine.Object.DestroyImmediate(rt);report.Add("PASS static preview rendered from native carrot prefabs at runtime grid coordinates");state.GetField("LastSelectedPlantName",f).SetValue(null,"sapling_carrot");type("PlantEasily").GetMethod("ClearSession",f).Invoke(null,null);if(state.GetField("LastSelectedPlantName",f).GetValue(null)!=null)throw new Exception("Session not cleared");report.Add("PASS session state cleared");Player.m_localPlayer=old;UnityEngine.Object.DestroyImmediate(host);
File.WriteAllLines("../../../Tools/AugaWork/planteasily-checks.txt",report);
}}