using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using System.Runtime.Serialization;using UnityEngine;using UnityEditor;using UnityEngine.UI;using TMPro;using AugaUnity;
public static class StatusOverviewCheck {
const string Root="D:/Valheim/valheim_Data/StreamingAssets/SoftRef/";static Dictionary<string,List<string>> deps=new Dictionary<string,List<string>>();static Dictionary<string,AssetBundle> bundles=new Dictionary<string,AssetBundle>();static void Load(string id){if(bundles.ContainsKey(id))return;bundles[id]=null;if(deps.ContainsKey(id))foreach(var d in deps[id])Load(d);bundles[id]=AssetBundle.LoadFromFile(Root+"Bundles/"+id);}
static Sprite Icon(Sprite original){foreach(var b in bundles.Values.Where(x=>x))foreach(var n in b.GetAllAssetNames().Where(n=>n.EndsWith(".spriteatlas"))){var atlas=b.LoadAsset<UnityEngine.U2D.SpriteAtlas>(n);var sprite=atlas.GetSprite(original.name);if(!sprite)continue;var entries=(Newtonsoft.Json.Linq.JArray)Newtonsoft.Json.Linq.JObject.Parse(EditorJsonUtility.ToJson(atlas))["SpriteAtlas"]["m_RenderDataMap"];var key=Newtonsoft.Json.Linq.JObject.Parse(EditorJsonUtility.ToJson(sprite))["Sprite"]["m_RenderDataKey"]["first"].ToString();int index=Enumerable.Range(0,entries.Count).First(i=>entries[i]["first"]["first"].ToString()==key);var r=entries[index]["second"]["textureRect"];var texture=(Texture2D)new SerializedObject(atlas).FindProperty("m_RenderDataMap").GetArrayElementAtIndex(index).FindPropertyRelative("second.texture").objectReferenceValue;return Sprite.Create(texture,new Rect((float)r["x"],(float)r["y"],(float)r["width"],(float)r["height"]),new Vector2(.5f,.5f),100);}return original;}
public static void Run(){AppDomain.CurrentDomain.AssemblyResolve+=(s,a)=>{var p=Path.GetFullPath("../../../Libs/"+new AssemblyName(a.Name).Name+".dll");return File.Exists(p)?Assembly.LoadFrom(p):null;};
var plugin=Assembly.LoadFrom(Path.GetFullPath("../../../Packages/Overhaul/Overhaul.dll"));const BindingFlags F=BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Static|BindingFlags.Instance;plugin.GetType("Overhaul.IntegratedUi").GetMethod("LoadDependencies",F).Invoke(null,null);
var loc=(Localization)FormatterServices.GetUninitializedObject(typeof(Localization));foreach(var f in typeof(Localization).GetFields(F).Where(f=>!f.IsStatic)){if(f.FieldType==typeof(char[]))f.SetValue(loc," (){}[]+-!?/\\&%,.:-=<>\n".ToCharArray());else if(f.FieldType==typeof(System.Text.StringBuilder))f.SetValue(loc,new System.Text.StringBuilder());else if(f.FieldType.IsGenericType&&(f.FieldType.GetGenericTypeDefinition()==typeof(Dictionary<,>)||f.FieldType.GetGenericTypeDefinition()==typeof(List<>)))f.SetValue(loc,Activator.CreateInstance(f.FieldType));else if(f.Name=="m_cache")f.SetValue(loc,Activator.CreateInstance(f.FieldType,new object[]{100}));}typeof(Localization).GetField("m_instance",F).SetValue(null,loc);plugin.GetType("Auga.Auga").GetMethod("LoadTranslations",F).Invoke(null,new object[]{loc,"French"});
var paths=new Dictionary<string,string>();string current=null,bundle=null;bool assets=false;foreach(var line in File.ReadAllLines(Root+"manifest_extended").Concat(File.ReadAllLines(Root+"manifest"))){if(line=="bundle dependencies:")assets=false;else if(line.StartsWith("asset locations:"))assets=true;else if(!assets){if(line.StartsWith("- bundle: ")){current=line.Substring(10).Trim();deps[current]=new List<string>();}else if(current!=null&&line.StartsWith("  - "))deps[current].Add(line.Substring(4).Trim());}else if(line.StartsWith("  bundle: "))bundle=line.Substring(10).Trim();else if(line.StartsWith("  path in bundle: "))paths[line.Substring(18).Trim()]=bundle;}
foreach(var a in paths.Where(x=>x.Key.EndsWith(".spriteatlas"))){Load(a.Value);var atlas=bundles[a.Value].LoadAsset<UnityEngine.U2D.SpriteAtlas>(a.Key);if(atlas)typeof(UnityEngine.U2D.SpriteAtlasManager).GetMethod("Register",BindingFlags.NonPublic|BindingFlags.Static).Invoke(null,new object[]{atlas});} var ab=AssetBundle.LoadFromFile("AssetBundles/augaassets");var host=new GameObject("Preview",typeof(Canvas));var canvas=host.GetComponent<Canvas>();var camGo=new GameObject("Camera",typeof(Camera));var cam=camGo.GetComponent<Camera>();cam.orthographic=true;cam.orthographicSize=210;cam.transform.position=new Vector3(0,0,-10);cam.clearFlags=CameraClearFlags.SolidColor;cam.backgroundColor=new Color(.12f,.14f,.13f);cam.cullingMask=1<<30;canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=cam;canvas.planeDistance=1;canvas.referencePixelsPerUnit=50;
var panel=UnityEngine.Object.Instantiate(ab.LoadAsset<GameObject>("HUD").transform.Find("hudroot/StatusOverview").gameObject,host.transform,false);var r=(RectTransform)panel.transform;r.anchorMin=r.anchorMax=r.pivot=new Vector2(.5f,1);r.anchoredPosition=new Vector2(0,-20);panel.transform.Find("Biome/Content").GetComponent<TMP_Text>().text="Prairies";panel.transform.Find("Clock").GetComponent<TMP_Text>().text="14:35";
var controller=panel.GetComponentInChildren<AugaStatusEffects>();if(!controller.EffectPrefab||controller.EffectsContainer!=controller.gameObject)throw new Exception("Broken effect bindings");controller.enabled=false;
foreach(var name in new[]{"BeltStrength","Wishbone","MeadHealthMinor","MeadStaminaMinor"}){var p=paths.First(x=>x.Key.EndsWith("/"+name+".prefab",StringComparison.OrdinalIgnoreCase));Load(p.Value);var item=bundles[p.Value].LoadAsset<GameObject>(p.Key).GetComponent<ItemDrop>().m_itemData;var se=item.m_shared.m_equipStatusEffect?item.m_shared.m_equipStatusEffect:item.m_shared.m_consumeStatusEffect;if(!se)throw new Exception("No effect: "+name);var effect=UnityEngine.Object.Instantiate(controller.EffectPrefab,controller.EffectsContainer.transform,false);effect.Index=-1;effect.UpdateStatusEffect(se);effect.Icon.sprite=Icon(se.m_icon);effect.gameObject.SetActive(true);}
var rt=new RenderTexture(340,420,24);cam.targetTexture=rt;foreach(var t in host.GetComponentsInChildren<Transform>(true))t.gameObject.layer=30;Canvas.ForceUpdateCanvases();LayoutRebuilder.ForceRebuildLayoutImmediate(r);Canvas.ForceUpdateCanvases();cam.Render();RenderTexture.active=rt;var tex=new Texture2D(340,420,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,340,420),0,0);tex.Apply();File.WriteAllBytes("../../../Tools/AugaWork/status-overview-preview.png",tex.EncodeToPNG());File.WriteAllText("../../../Tools/AugaWork/status-overview-check.txt","PASS actual bundled prefab, biome/clock, native 4 status effects with timers, effect container references. "+plugin.GetName().Version);
}}


