using System; using UnityEditor; using System.Reflection;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
public static class TarDrainCheck {
const string Root="D:/Valheim/valheim_Data/StreamingAssets/SoftRef/";
static Dictionary<string,List<string>> deps=new Dictionary<string,List<string>>();
static Dictionary<string,AssetBundle> bundles=new Dictionary<string,AssetBundle>();
static void Load(string id){if(bundles.ContainsKey(id))return;bundles[id]=null;if(deps.ContainsKey(id))foreach(var d in deps[id])Load(d);bundles[id]=AssetBundle.LoadFromFile(Root+"Bundles/"+id);}
static Sprite Icon(Sprite original){foreach(var b in bundles.Values.Where(x=>x))foreach(var n in b.GetAllAssetNames().Where(n=>n.EndsWith(".spriteatlas"))){var atlas=b.LoadAsset<UnityEngine.U2D.SpriteAtlas>(n);var sprite=atlas.GetSprite(original.name);if(!sprite)continue;var entries=(Newtonsoft.Json.Linq.JArray)Newtonsoft.Json.Linq.JObject.Parse(EditorJsonUtility.ToJson(atlas))["SpriteAtlas"]["m_RenderDataMap"];var key=Newtonsoft.Json.Linq.JObject.Parse(EditorJsonUtility.ToJson(sprite))["Sprite"]["m_RenderDataKey"]["first"].ToString();int index=Enumerable.Range(0,entries.Count).First(i=>entries[i]["first"]["first"].ToString()==key);var r=entries[index]["second"]["textureRect"];var texture=(Texture2D)new SerializedObject(atlas).FindProperty("m_RenderDataMap").GetArrayElementAtIndex(index).FindPropertyRelative("second.texture").objectReferenceValue;return Sprite.Create(texture,new Rect((float)r["x"],(float)r["y"],(float)r["width"],(float)r["height"]),new Vector2(.5f,.5f),100);}return original;}
public static void Run(){ AppDomain.CurrentDomain.AssemblyResolve+=(s,a)=>{var p=Path.GetFullPath("../../../Libs/"+new System.Reflection.AssemblyName(a.Name).Name+".dll");return File.Exists(p)?System.Reflection.Assembly.LoadFrom(p):null;};
var paths=new Dictionary<string,string>();string current=null,bundle=null;bool assets=false;
foreach(var line in File.ReadAllLines(Root+"manifest_extended").Concat(File.ReadAllLines(Root+"manifest"))){
if(line=="bundle dependencies:")assets=false;else if(line.StartsWith("asset locations:"))assets=true;
else if(!assets){if(line.StartsWith("- bundle: ")){current=line.Substring(10).Trim();deps[current]=new List<string>();}else if(current!=null&&line.StartsWith("  - "))deps[current].Add(line.Substring(4).Trim());}
else if(line.StartsWith("  bundle: "))bundle=line.Substring(10).Trim();else if(line.StartsWith("  path in bundle: "))paths[line.Substring(18).Trim()]=bundle;
}
GameObject Native(string name){var p=paths.First(p=>p.Key.EndsWith("/"+name+".prefab",StringComparison.OrdinalIgnoreCase));Load(p.Value);return bundles[p.Value].LoadAsset<GameObject>(p.Key);}
var plugin=Assembly.LoadFrom(Path.GetFullPath("../../../Packages/Overhaul/Overhaul.dll"));type=plugin.GetType("Overhaul.TarDrain");var host=new GameObject("Inactive tar test fixtures");host.SetActive(false);
var native=Native("mud_road_v2");var stone=Native("Stone").GetComponent<ItemDrop>();var tar=Native("Tar").GetComponent<ItemDrop>();var action=UnityEngine.Object.Instantiate(native,host.transform);action.name="Overhaul_HoeDrainTar";var actionIcon=(Sprite)Call("GetIcon");Call("Configure",action,stone,actionIcon);var piece=action.GetComponent<Piece>();
var sprite=Icon(piece.m_icon);var rect=sprite.rect;var rt=RenderTexture.GetTemporary((int)rect.width,(int)rect.height,0,RenderTextureFormat.ARGB32);Graphics.Blit(sprite.texture,rt,new Vector2(rect.width/sprite.texture.width,rect.height/sprite.texture.height),new Vector2(rect.x/sprite.texture.width,rect.y/sprite.texture.height));RenderTexture.active=rt;var texture=new Texture2D(rt.width,rt.height,TextureFormat.RGBA32,false);texture.ReadPixels(new Rect(0,0,rt.width,rt.height),0,0);texture.Apply();File.WriteAllBytes("../../../Tools/AugaWork/hoe-drain-tar-current-icon.png",texture.EncodeToPNG());RenderTexture.active=null;RenderTexture.ReleaseTemporary(rt);
Check(!action.GetComponent<TerrainOp>()&&!action.GetComponent<TerrainModifier>(),"Action contains no terrain editing component");Check(native.GetComponent<TerrainOp>()!=null,"Native hoe action untouched");Check(piece.m_resources.Length==1&&piece.m_resources[0].m_resItem==stone&&piece.m_resources[0].m_amount==5&&!piece.m_resources[0].m_recover,"Exactly five stone, no refund exploit");Check(piece.m_icon==actionIcon&&piece.m_name=="$overhaul_hoe_drain_tar","Embedded drain icon and localized label");Check(piece.m_groundPiece&&!piece.m_allowAltGroundPlacement&&!piece.m_harvest,"Targets aimed ground without harvesting items");Check(action.GetComponents<IPlaced>().Length==2,"Only native Piece and drain placement callbacks");
var net=host.AddComponent<ZNet>();typeof(ZNet).GetField("m_instance",F).SetValue(null,net);var game=host.AddComponent<Game>();typeof(Game).GetProperty("instance",F).SetValue(null,game);new ZRoutedRpc(true);var manager=new ZDOMan(512);var scene=host.AddComponent<ZNetScene>();typeof(ZNetScene).GetField("s_instance",F).SetValue(null,scene);
var actorPrefab=new GameObject("PlayerTest");actorPrefab.transform.SetParent(host.transform);actorPrefab.AddComponent<Player>();scene.m_namedPrefabs[actorPrefab.name.GetStableHashCode()]=actorPrefab;
var actor=manager.CreateNewZDO(Vector3.zero,actorPrefab.name.GetStableHashCode());actor.SetPrefab(actorPrefab.name.GetStableHashCode());actor.SetOwner(ZNet.GetUID());actor.Set(ZDOVars.s_playerID,73L);
var player=host.AddComponent<Player>();var resource=stone.m_itemData.Clone();resource.m_dropPrefab=stone.gameObject;resource.m_stack=5;player.GetInventory().AddItem(resource);player.ConsumeResources(piece.m_resources,0);Check(player.GetInventory().CountItems(stone.m_itemData.m_shared.m_name)==0,"Native consumption deducts exactly five stone");
var harmonyType=Assembly.LoadFrom(Path.GetFullPath("../../../Libs/0Harmony.dll")).GetType("HarmonyLib.Harmony");
var harmony=Activator.CreateInstance(harmonyType,new object[]{"overhaul.test.tar-quality"});
foreach(var patchName in new[]{"FilterActions","ValidatePlacement"}){var processor=harmonyType.GetMethod("CreateClassProcessor",new[]{typeof(Type)}).Invoke(harmony,new object[]{type.GetNestedType(patchName,F)});processor.GetType().GetMethod("Patch").Invoke(processor,null);}
var table=host.AddComponent<PieceTable>();table.m_pieces.Add(action);table.m_pieces.Add(native);
var hoe=new ItemDrop.ItemData{m_quality=1,m_shared=new ItemDrop.ItemData.SharedData{m_buildPieces=table}};
typeof(Humanoid).GetField("m_rightItem",F).SetValue(player,hoe);
foreach(var quality in new[]{1,2,3,4}){
hoe.m_quality=quality;bool allowed=quality>=3;
Check((bool)Call("CanUse",player)==allowed,"Quality gate "+quality);
table.UpdateAvailable(new HashSet<string>(),player,false,true);
Check(table.m_availablePieces.Contains(piece)==allowed&&table.m_enabledPieces.Contains(piece)==allowed,"Native menu availability "+quality);
Check(table.m_availablePiecesByCategory.Any(category=>category.Contains(piece))==allowed,"Category availability "+quality);
Check(table.m_availablePieces.Contains(native.GetComponent<Piece>()),"Other hoe action preserved "+quality);
if(!allowed)Check(!player.TryPlacePiece(piece),"Stale selection blocked before native placement "+quality);
}
hoe.m_quality=1;table.UpdateAvailable(new HashSet<string>(),player,false,true);Check(!table.m_availablePieces.Contains(piece),"Switching back to low quality hides action");
typeof(Humanoid).GetField("m_rightItem",F).SetValue(player,null);Check(!(bool)Call("CanUse",player),"No equipped tool rejected");
hoe.m_quality=4;hoe.m_shared.m_buildPieces=null;typeof(Humanoid).GetField("m_rightItem",F).SetValue(player,hoe);Check(!(bool)Call("CanUse",player),"Other level four item rejected");
harmonyType.GetMethod("UnpatchSelf").Invoke(harmony,null);
LiquidVolume Volume(string name,int width=8,float scale=1f){var go=new GameObject(name);go.transform.SetParent(host.transform);var v=go.AddComponent<ZNetView>();v.m_zdo=manager.CreateNewZDO(Vector3.zero,name.GetStableHashCode());v.m_zdo.SetOwner(ZNet.GetUID());var l=go.AddComponent<LiquidVolume>();l.m_nview=v;l.m_width=width;l.m_scale=scale;l.m_maxDepth=20;l.m_depths=Enumerable.Repeat(3f,(width+1)*(width+1)).ToList();l.m_heights=Enumerable.Repeat(0f,(width+1)*(width+1)).ToList();return l;}
var liquid=Volume("TarTest");var terrainBefore=liquid.m_heights.ToArray();var depthsBefore=liquid.m_depths.ToArray();var loot=new GameObject("Loot untouched");loot.transform.SetParent(host.transform);loot.AddComponent<Pickable>();var lootPos=loot.transform.position;
float before=liquid.m_depths.Sum();float probe=(float)Call("ChangeDepths",liquid,Vector3.zero,false);Check(probe==26f&&liquid.m_depths.SequenceEqual(depthsBefore),"Read-only target probe, radius two contains thirteen cells");float removed=(float)Call("ChangeDepths",liquid,Vector3.zero,true);Check(Mathf.Abs(before-liquid.m_depths.Sum()-removed)<.001f&&removed==26,"Exact removed volume");Check(liquid.m_depths[4*9+4]==1&&liquid.m_depths[0]==3,"Center drained, distant cells untouched");Check(liquid.m_heights.SequenceEqual(terrainBefore)&&loot&&loot.transform.position==lootPos,"Terrain heights and nearby loot unchanged");Check(liquid.m_dirty&&liquid.m_needsSaving,"Mesh and persistence dirty flags");Call("ChangeDepths",liquid,Vector3.zero,true);Check(liquid.m_depths[4*9+4]==0&&liquid.m_depths.All(d=>d>=0),"No negative depth");Check((float)Call("ChangeDepths",liquid,Vector3.zero,true)==0,"Empty area does nothing");Check((float)Call("ChangeDepths",liquid,new Vector3(1000,0,1000),true)==0,"Outside grid does nothing");Check((float)Call("ChangeDepths",liquid,new Vector3(float.NaN,0,0),true)==0,"Nonfinite target rejected");Check((float)Call("ChangeDepths",liquid,new Vector3(0,500,0),true)==0,"Different altitude rejected");liquid.m_liquidType=LiquidType.Water;before=liquid.m_depths.Sum();Call("ChangeDepths",liquid,Vector3.zero,true);Check(liquid.m_depths.Sum()==before,"Water cannot be drained");liquid.m_liquidType=LiquidType.Tar;
var scaled=Volume("ScaledTar",8,2f);Check((float)Call("ChangeDepths",scaled,Vector3.zero,false)==10f,"World-space radius respects grid scale");scaled.transform.position=new Vector3(100,10,200);Check((float)Call("ChangeDepths",scaled,new Vector3(100,10,200),false)==10f,"Translated grid targeting");
var authoritative=Volume("NetworkTar");before=authoritative.m_depths.Sum();Call("Receive",authoritative,ZNet.GetUID()+1,actor.m_uid,Vector3.zero);Check(authoritative.m_depths.Sum()==before,"Spoofed actor owner rejected");actor.SetPosition(new Vector3(100,0,0));Call("Receive",authoritative,ZNet.GetUID(),actor.m_uid,Vector3.zero);Check(authoritative.m_depths.Sum()==before,"Remote out-of-range request rejected");actor.SetPosition(Vector3.zero);authoritative.m_nview.GetZDO().SetOwner(ZNet.GetUID()+1);Call("Receive",authoritative,ZNet.GetUID(),actor.m_uid,Vector3.zero);Check(authoritative.m_depths.Sum()==before,"Only liquid owner mutates");authoritative.m_nview.GetZDO().SetOwner(ZNet.GetUID());
var wardGo=new GameObject("Ward");wardGo.transform.SetParent(host.transform);var ward=wardGo.AddComponent<PrivateArea>();ward.m_piece=wardGo.AddComponent<Piece>();ward.m_piece.m_creator=99;ward.m_radius=10;ward.m_nview=wardGo.AddComponent<ZNetView>();ward.m_nview.m_zdo=manager.CreateNewZDO(Vector3.zero,"Ward".GetStableHashCode());ward.m_nview.m_zdo.SetOwner(ZNet.GetUID());ward.m_nview.GetZDO().Set(ZDOVars.s_enabled,true);PrivateArea.m_allAreas.Add(ward);Call("Receive",authoritative,ZNet.GetUID(),actor.m_uid,Vector3.zero);Check(authoritative.m_depths.Sum()==before,"Foreign ward blocks drain");ward.m_piece.m_creator=73;Call("Receive",authoritative,ZNet.GetUID(),actor.m_uid,Vector3.zero);Check(authoritative.m_depths.Sum()==before-26,"Authorized network drain accepted");PrivateArea.m_allAreas.Remove(ward);Check(authoritative.m_nview.GetZDO().GetByteArray(ZDOVars.s_liquidData)!=null,"Saved to native liquid ZDO immediately");
var replica=Volume("Replica");replica.m_nview.m_zdo=authoritative.m_nview.m_zdo;replica.Load();Check(Mathf.Abs(replica.m_depths.Sum()-authoritative.m_depths.Sum())<.001f,"Native save/load preserves drained quantity");Check(replica.m_heights.SequenceEqual(terrainBefore),"Loading drained data preserves ground heights");
// Native fluid simulation redistributes the reduced amount; it must not restore removed tar.
var sim=Volume("Simulation",16);for(int z=0;z<=16;z++)for(int x=0;x<=16;x++){bool inside=x>=5&&x<=11&&z>=5&&z<=11;sim.m_depths[z*17+x]=inside?3f:0f;sim.m_heights[z*17+x]=inside?0f:20f;}var simGround=sim.m_heights.ToArray();Call("ChangeDepths",sim,Vector3.zero,true);float total=sim.m_depths.Sum();for(int step=0;step<100;step++)sim.UpdateLiquid(.05f);Check(Mathf.Abs(sim.m_depths.Sum()-total)<.01f,"Native simulation keeps the reduced total");Check(sim.m_heights.SequenceEqual(simGround),"Simulation did not alter terrain heights");
Check(sim.m_depths[8*17+8]<2.6f&&sim.m_depths[8*17+8]>1f,"Flow refills local depression but basin level stays lower");File.WriteAllText("../../../Tools/AugaWork/tar-drain-check.txt","PASS "+checks+" native prefab, consumption, liquid grid, authority, ward and native save/load/simulation checks. "+plugin.GetName().Version);
}
const BindingFlags F=BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Static|BindingFlags.Instance;static Type type;static int checks;static object Call(string name,params object[] args)=>type.GetMethod(name,F).Invoke(null,args);static void Check(bool b,string m){if(!b)throw new Exception(m);checks++;}
}




