param([Parameter(Mandatory = $true)][string]$ProjectDirectory)
$ErrorActionPreference = 'Stop'
$statePath = Join-Path $ProjectDirectory 'Version.json'
$outputPath = Join-Path $ProjectDirectory 'Properties\BuildVersion.g.cs'
$state = [IO.File]::ReadAllText($statePath) | ConvertFrom-Json
foreach ($part in @('Major', 'Minor', 'Patch', 'Revision')) {
    if ([string]$state.$part -notmatch '^\d+$' -or [long]$state.$part -gt 65534) {
        throw "Invalid version component: $part"
    }
}
# A new Major, Minor or Patch (a public release) restarts the build revision at 0.
$series = '{0}.{1}.{2}' -f $state.Major, $state.Minor, $state.Patch
if ($series -ne $state.LastSeries) {
    $state.Revision = 0
} else {
    $state.Revision = [int]$state.Revision + 1
}
if ($state.Revision -gt 65534) { throw 'Version revision exhausted. Change Major or Minor.' }
$state.LastSeries = $series
$version = '{0}.{1}.{2}.{3}' -f $state.Major, $state.Minor, $state.Patch, $state.Revision
$code = "// Generated by Increment-Version.ps1. Edit Version.json instead.`r`nnamespace Overhaul { internal static class BuildVersion { internal const string Value = `"$version`"; } }`r`n"
[IO.Directory]::CreateDirectory((Split-Path $outputPath)) | Out-Null
$utf8 = [Text.UTF8Encoding]::new($false)
[IO.File]::WriteAllText($outputPath, $code, $utf8)
[IO.File]::WriteAllText($statePath, ($state | ConvertTo-Json) + "`r`n", $utf8)
Write-Output "Overhaul version: $version"
