using System.IO;
using System.Linq;
using System.Text;

namespace Overhaul.Rarity
{
    // RarityItems.txt, next to the plugin: the gear items of each biome of RaritySystem.cfg, and the weapons, armour,
    // shields, tools, accessories and trinkets players can craft, loot or buy that no biome lists. Written once the
    // game data is loaded, to check the Biome sections.
    internal static class BiomeReport
    {
        internal const string FileName = "RarityItems.txt";

        internal static void Write()
        {
            if (!ObjectDB.instance) return;
            var creatures = CreatureItems();
            var looted = LootedItems();
            var sold = SoldItems();
            var items = ObjectDB.instance.m_items.Where(p => p && !creatures.Contains(p.name)).Select(p => p.GetComponent<ItemDrop>()).Where(d => d && Gear(d.m_itemData))
                .Select(d =>
                {
                    Recipe recipe = ObjectDB.instance.GetRecipe(d.m_itemData);
                    string name = d.gameObject.name;
                    var sources = new[] { recipe != null && recipe.m_enabled ? "craft" : null, looted.Contains(name) ? "loot" : null, sold.Contains(name) ? "trader" : null }.Where(s => s != null).ToArray();
                    return new { Prefab = name, Item = d.m_itemData, Biome = Enchantments.Biome(d.m_itemData, name), Sources = sources.Length > 0 ? string.Join("+", sources) : "not obtainable" };
                })
                .OrderBy(i => i.Prefab).ToList();
            var text = new StringBuilder();
            text.AppendLine("# Generated by Overhaul: gear items by rarity biome (prefab | name | type | obtained by)");
            foreach (var biome in RarityConfig.Current.Biomes)
            {
                var inBiome = items.Where(i => i.Biome == biome.Order).ToList();
                text.AppendLine().AppendLine("[" + biome.Id + "] " + inBiome.Count + " items");
                foreach (var i in inBiome) text.AppendLine(Line(i.Prefab, i.Item, i.Sources));
            }
            // An item nobody can craft, loot or buy is not in the game: only the obtainable ones are worth checking.
            var outside = items.Where(i => i.Biome < 0 && i.Sources != "not obtainable").ToList();
            text.AppendLine().AppendLine("[NotListed] " + outside.Count + " obtainable items outside the rarity system");
            foreach (var i in outside) text.AppendLine(Line(i.Prefab, i.Item, i.Sources));
            string path = Path.Combine(Path.GetDirectoryName(typeof(BiomeReport).Assembly.Location), FileName);
            File.WriteAllText(path, text.ToString());
            Utility.Log.LogInfo("Rarity biomes of " + items.Count + " gear items written to " + path);
        }

        // Items dropped by creatures, chests, plants, trees, rocks and other destructibles, fish, and the rarity loot lists.
        private static System.Collections.Generic.HashSet<string> LootedItems()
        {
            var names = new System.Collections.Generic.HashSet<string>();
            void Table(DropTable table) { if (table?.m_drops != null) foreach (var drop in table.m_drops) if (drop.m_item) names.Add(drop.m_item.name); }
            if (ZNetScene.instance)
                foreach (var prefab in ZNetScene.instance.m_prefabs)
                {
                    if (!prefab) continue;
                    foreach (var c in prefab.GetComponentsInChildren<CharacterDrop>(true)) if (c.m_drops != null) foreach (var drop in c.m_drops) if (drop.m_prefab) names.Add(drop.m_prefab.name);
                    foreach (var c in prefab.GetComponentsInChildren<DropOnDestroyed>(true)) Table(c.m_dropWhenDestroyed);
                    foreach (var c in prefab.GetComponentsInChildren<Container>(true)) Table(c.m_defaultItems);
                    foreach (var c in prefab.GetComponentsInChildren<Pickable>(true)) { if (c.m_itemPrefab) names.Add(c.m_itemPrefab.name); Table(c.m_extraDrops); }
                    foreach (var c in prefab.GetComponentsInChildren<LootSpawner>(true)) Table(c.m_items);
                    foreach (var c in prefab.GetComponentsInChildren<TreeLog>(true)) Table(c.m_dropWhenDestroyed);
                    foreach (var c in prefab.GetComponentsInChildren<TreeBase>(true)) Table(c.m_dropWhenDestroyed);
                    foreach (var c in prefab.GetComponentsInChildren<MineRock>(true)) Table(c.m_dropItems);
                    foreach (var c in prefab.GetComponentsInChildren<MineRock5>(true)) Table(c.m_dropItems);
                    foreach (var c in prefab.GetComponentsInChildren<Fish>(true)) Table(c.m_extraDrops);
                }
            foreach (var list in RarityConfig.Current.LootLists.Values) foreach (string item in list.Items) names.Add(item);
            return names;
        }

        // Items sold by the traders (Haldor, Hildir, the Bog Witch...).
        private static System.Collections.Generic.HashSet<string> SoldItems()
        {
            var names = new System.Collections.Generic.HashSet<string>();
            if (ZNetScene.instance)
                foreach (var prefab in ZNetScene.instance.m_prefabs)
                {
                    var trader = prefab ? prefab.GetComponentInChildren<Trader>(true) : null;
                    if (trader?.m_items != null) foreach (var item in trader.m_items) if (item.m_prefab) names.Add(item.m_prefab.gameObject.name);
                }
            return names;
        }

        // A dedicated server has no local player to trigger the validation: it writes the report once the world loads.
        [HarmonyLib.HarmonyPatch(typeof(Game), "Start")]
        private static class DedicatedServer { private static void Postfix() { if (ZNet.instance && ZNet.instance.IsDedicated()) Write(); } }

        // Attacks and gear of creatures (their default and random items), which players never get.
        private static System.Collections.Generic.HashSet<string> CreatureItems()
        {
            var names = new System.Collections.Generic.HashSet<string>();
            if (!ZNetScene.instance) return names;
            void Add(UnityEngine.GameObject[] list) { if (list != null) foreach (var item in list) if (item) names.Add(item.name); }
            foreach (var prefab in ZNetScene.instance.m_prefabs)
            {
                var humanoid = prefab ? prefab.GetComponent<Humanoid>() : null;
                if (!humanoid || humanoid is Player) continue;
                Add(humanoid.m_defaultItems); Add(humanoid.m_randomWeapon); Add(humanoid.m_randomArmor); Add(humanoid.m_randomShield);
                if (humanoid.m_randomSets != null) foreach (var set in humanoid.m_randomSets) Add(set.m_items);
                if (humanoid.m_randomItems != null) foreach (var random in humanoid.m_randomItems) if (random.m_prefab) names.Add(random.m_prefab.name);
            }
            return names;
        }

        private static bool Gear(ItemDrop.ItemData item) => ItemRarity.Gear(item) || item.m_shared.m_itemType == ItemDrop.ItemData.ItemType.Tool;

        private static string Line(string prefab, ItemDrop.ItemData item, string reason) =>
            "  " + prefab + " | " + Localization.instance.Localize(item.m_shared.m_name) + " | " + item.m_shared.m_itemType + " | " + reason;
    }
}
