using System.IO;
using System.Linq;
using System.Text;

namespace Overhaul.Rarity
{
    // RarityItems.txt, next to the plugin: every weapon, armour, shield, tool, accessory and trinket of the game,
    // grouped by the biome the rarity system gives it, with the material that decided it. Written once the game
    // data is loaded, to check the Biome sections of RaritySystem.cfg.
    internal static class BiomeReport
    {
        internal const string FileName = "RarityItems.txt";

        internal static void Write()
        {
            if (!ObjectDB.instance) return;
            var biomes = RarityConfig.Current.Biomes;
            var items = ObjectDB.instance.m_items.Where(p => p).Select(p => p.GetComponent<ItemDrop>()).Where(d => d && Gear(d.m_itemData))
                .Select(d => new { Prefab = d.gameObject.name, Item = d.m_itemData, Recipe = ObjectDB.instance.GetRecipe(d.m_itemData) })
                .OrderBy(i => i.Prefab).ToList();
            var text = new StringBuilder();
            text.AppendLine("# Generated by Overhaul: gear items by rarity biome (prefab | name | type | decided by)");
            foreach (var biome in biomes)
            {
                var inBiome = items.Where(i => i.Recipe != null || biome.Items.Contains(i.Prefab)).Where(i => Enchantments.Biome(i.Item) == biome.Order).ToList();
                text.AppendLine().AppendLine("[" + biome.Id + "] " + inBiome.Count + " items");
                foreach (var i in inBiome) text.AppendLine(Line(i.Prefab, i.Item, biome.Items.Contains(i.Prefab) ? "Items list" : Decider(i.Recipe, biome)));
            }
            var noRecipe = items.Where(i => i.Recipe == null && !biomes.Any(b => b.Items.Contains(i.Prefab))).ToList();
            text.AppendLine().AppendLine("[NoRecipe] " + noRecipe.Count + " items (first biome unless listed in a biome's Items)");
            foreach (var i in noRecipe) text.AppendLine(Line(i.Prefab, i.Item, "no recipe"));
            string path = Path.Combine(Path.GetDirectoryName(typeof(BiomeReport).Assembly.Location), FileName);
            File.WriteAllText(path, text.ToString());
            Utility.Log.LogInfo("Rarity biomes of " + items.Count + " gear items written to " + path);
        }

        // A dedicated server has no local player to trigger the validation: it writes the report once the world loads.
        [HarmonyLib.HarmonyPatch(typeof(Game), "Start")]
        private static class DedicatedServer { private static void Postfix() { if (ZNet.instance && ZNet.instance.IsDedicated()) Write(); } }

        private static bool Gear(ItemDrop.ItemData item) => ItemRarity.Gear(item) || item.m_shared.m_itemType == ItemDrop.ItemData.ItemType.Tool;

        private static string Line(string prefab, ItemDrop.ItemData item, string reason) =>
            "  " + prefab + " | " + Localization.instance.Localize(item.m_shared.m_name) + " | " + item.m_shared.m_itemType + " | " + reason;

        // The recipe materials belonging to the item's biome.
        private static string Decider(Recipe recipe, BiomeDef biome)
        {
            var materials = recipe.m_resources.Where(r => r.m_resItem && biome.Materials.Contains(r.m_resItem.gameObject.name)).Select(r => r.m_resItem.gameObject.name).ToArray();
            return materials.Length > 0 ? string.Join(", ", materials) : "no material of a later biome";
        }
    }
}
