using System.IO;
using System.Linq;
using System.Text;

namespace Overhaul.Rarity
{
    // RarityItems.txt, next to the plugin: every weapon, armour, shield, tool, accessory and trinket players can craft, loot or buy,
    // grouped by the biome the rarity system gives it, with the material that decided it. Written once the game
    // data is loaded, to check the Biome sections of RaritySystem.cfg.
    internal static class BiomeReport
    {
        internal const string FileName = "RarityItems.txt";

        internal static void Write()
        {
            if (!ObjectDB.instance) return;
            var biomes = RarityConfig.Current.Biomes;
            var creatures = CreatureItems();
            var looted = LootedItems();
            var sold = SoldItems();
            var items = ObjectDB.instance.m_items.Where(p => p && !creatures.Contains(p.name)).Select(p => p.GetComponent<ItemDrop>()).Where(d => d && Gear(d.m_itemData))
                .Select(d =>
                {
                    Recipe recipe = ObjectDB.instance.GetRecipe(d.m_itemData);
                    if (recipe != null && !recipe.m_enabled) recipe = null;
                    string name = d.gameObject.name;
                    var sources = new[] { recipe != null ? "craft" : null, looted.Contains(name) ? "loot" : null, sold.Contains(name) ? "trader" : null }.Where(s => s != null).ToArray();
                    return new { Prefab = name, Item = d.m_itemData, Recipe = recipe, Sources = string.Join("+", sources) };
                })
                // An item nobody can craft, loot or buy is not in the game.
                .Where(i => i.Sources.Length > 0)
                .OrderBy(i => i.Prefab).ToList();
            var text = new StringBuilder();
            text.AppendLine("# Generated by Overhaul: obtainable gear items by rarity biome (prefab | name | type | obtained by | biome decided by)");
            foreach (var biome in biomes)
            {
                var inBiome = items.Where(i => i.Recipe != null || biome.Items.Contains(i.Prefab)).Where(i => Enchantments.Biome(i.Item, i.Prefab) == biome.Order).ToList();
                text.AppendLine().AppendLine("[" + biome.Id + "] " + inBiome.Count + " items");
                foreach (var i in inBiome) text.AppendLine(Line(i.Prefab, i.Item, i.Sources + " | " + (biome.Items.Contains(i.Prefab) ? "Items list" : Decider(i.Recipe, biome))));
            }
            var unplaced = items.Where(i => i.Recipe == null && !biomes.Any(b => b.Items.Contains(i.Prefab))).ToList();
            text.AppendLine().AppendLine("[Unplaced] " + unplaced.Count + " items without recipe (first biome unless listed in a biome's Items)");
            foreach (var i in unplaced) text.AppendLine(Line(i.Prefab, i.Item, i.Sources));
            string path = Path.Combine(Path.GetDirectoryName(typeof(BiomeReport).Assembly.Location), FileName);
            File.WriteAllText(path, text.ToString());
            Utility.Log.LogInfo("Rarity biomes of " + items.Count + " gear items written to " + path);
        }

        // Items dropped by creatures, chests, plants, trees, rocks and other destructibles, fish, and the rarity loot lists.
        private static System.Collections.Generic.HashSet<string> LootedItems()
        {
            var names = new System.Collections.Generic.HashSet<string>();
            void Table(DropTable table) { if (table?.m_drops != null) foreach (var drop in table.m_drops) if (drop.m_item) names.Add(drop.m_item.name); }
            if (ZNetScene.instance)
                foreach (var prefab in ZNetScene.instance.m_prefabs)
                {
                    if (!prefab) continue;
                    foreach (var c in prefab.GetComponentsInChildren<CharacterDrop>(true)) if (c.m_drops != null) foreach (var drop in c.m_drops) if (drop.m_prefab) names.Add(drop.m_prefab.name);
                    foreach (var c in prefab.GetComponentsInChildren<DropOnDestroyed>(true)) Table(c.m_dropWhenDestroyed);
                    foreach (var c in prefab.GetComponentsInChildren<Container>(true)) Table(c.m_defaultItems);
                    foreach (var c in prefab.GetComponentsInChildren<Pickable>(true)) { if (c.m_itemPrefab) names.Add(c.m_itemPrefab.name); Table(c.m_extraDrops); }
                    foreach (var c in prefab.GetComponentsInChildren<LootSpawner>(true)) Table(c.m_items);
                    foreach (var c in prefab.GetComponentsInChildren<TreeLog>(true)) Table(c.m_dropWhenDestroyed);
                    foreach (var c in prefab.GetComponentsInChildren<TreeBase>(true)) Table(c.m_dropWhenDestroyed);
                    foreach (var c in prefab.GetComponentsInChildren<MineRock>(true)) Table(c.m_dropItems);
                    foreach (var c in prefab.GetComponentsInChildren<MineRock5>(true)) Table(c.m_dropItems);
                    foreach (var c in prefab.GetComponentsInChildren<Fish>(true)) Table(c.m_extraDrops);
                }
            foreach (var list in RarityConfig.Current.LootLists.Values) foreach (string item in list.Items) names.Add(item);
            return names;
        }

        // Items sold by the traders (Haldor, Hildir, the Bog Witch...).
        private static System.Collections.Generic.HashSet<string> SoldItems()
        {
            var names = new System.Collections.Generic.HashSet<string>();
            if (ZNetScene.instance)
                foreach (var prefab in ZNetScene.instance.m_prefabs)
                {
                    var trader = prefab ? prefab.GetComponentInChildren<Trader>(true) : null;
                    if (trader?.m_items != null) foreach (var item in trader.m_items) if (item.m_prefab) names.Add(item.m_prefab.gameObject.name);
                }
            return names;
        }

        // A dedicated server has no local player to trigger the validation: it writes the report once the world loads.
        [HarmonyLib.HarmonyPatch(typeof(Game), "Start")]
        private static class DedicatedServer { private static void Postfix() { if (ZNet.instance && ZNet.instance.IsDedicated()) Write(); } }

        // Attacks and gear of creatures (their default and random items), which players never get.
        private static System.Collections.Generic.HashSet<string> CreatureItems()
        {
            var names = new System.Collections.Generic.HashSet<string>();
            if (!ZNetScene.instance) return names;
            void Add(UnityEngine.GameObject[] list) { if (list != null) foreach (var item in list) if (item) names.Add(item.name); }
            foreach (var prefab in ZNetScene.instance.m_prefabs)
            {
                var humanoid = prefab ? prefab.GetComponent<Humanoid>() : null;
                if (!humanoid || humanoid is Player) continue;
                Add(humanoid.m_defaultItems); Add(humanoid.m_randomWeapon); Add(humanoid.m_randomArmor); Add(humanoid.m_randomShield);
                if (humanoid.m_randomSets != null) foreach (var set in humanoid.m_randomSets) Add(set.m_items);
                if (humanoid.m_randomItems != null) foreach (var random in humanoid.m_randomItems) if (random.m_prefab) names.Add(random.m_prefab.name);
            }
            return names;
        }

        private static bool Gear(ItemDrop.ItemData item) => ItemRarity.Gear(item) || item.m_shared.m_itemType == ItemDrop.ItemData.ItemType.Tool;

        private static string Line(string prefab, ItemDrop.ItemData item, string reason) =>
            "  " + prefab + " | " + Localization.instance.Localize(item.m_shared.m_name) + " | " + item.m_shared.m_itemType + " | " + reason;

        // The recipe materials belonging to the item's biome.
        private static string Decider(Recipe recipe, BiomeDef biome)
        {
            var materials = recipe.m_resources.Where(r => r.m_resItem && biome.Materials.Contains(r.m_resItem.gameObject.name)).Select(r => r.m_resItem.gameObject.name).ToArray();
            return materials.Length > 0 ? string.Join(", ", materials) : "no material of a later biome";
        }
    }
}
